### ISSUE TITLE
Undefined variable: app_list_strings in

### ISSUE THREAD

**Issue by tuckdesign** [esimonetti/toothpaste#4]
When doing metadata rebuild I get:
Undefined variable: app_list_strings in /home/crmvendor/toothpaste/vendor/esimonetti/toothpaste/src/Sugar/Instance.php on line 133

Fix is easy. Patch is attached
[patch.txt](https://github.com/esimonetti/toothpaste/files/6175586/patch.txt)

**Comment by R3dian** [comment]
Found the same problem on my end as well. Initiated a pull request for @esimonetti to review and merge in the main repository.

**Comment by esimonetti** [comment]
Thanks, I am really not sure why I am not experiencing, but that's ok.
Now I will need to understand how to release a new version, as it has been a minute :)

Thanks for the contribution!
